apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stg-backend-app-3
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:ardikabs/demo-argocd-applicationset.git
              revision: HEAD
              files:
                - path: helm/*/.argocd.yaml
            selector:
              matchLabels:
                clusters.backend.stg.enabled: "true"
          - git:
              repoURL: git@github.com:ardikabs/demo-argocd-applicationset.git
              revision: HEAD
              files:
                - path: helm/defaults.yaml
  template:
    metadata:
      name: "stg-backend-{{ index .path.segments 1 }}-1"
      labels:
        systems.superbank.io/service: "{{ index .path.segments 1 }}"
      namespace: argocd
    spec:
      project: stg-backend-apps
      source:
        repoURL: git@github.com:ardikabs/demo-argocd-applicationset.git
        targetRevision: HEAD
        path: "helm/{{ index .path.segments 1 }}"
        helm:
          releaseName: "{{ index .path.segments 1 }}"
          valueFiles: []
          parameters: []
      destination:
        name: in-cluster
        namespace: "{{ .namespace }}"
      syncPolicy: {}
      ignoreDifferences: []
  templatePatch: |-
    {{- $defVal := .defaults.clusters.stg }}
    {{- $meta := .clusters.backend.stg }}
    spec:
      source:
        helm:
          valueFiles:
          {{- range $valueFile := default $defVal.helm.valueFiles (and (hasKey $meta "helm") $meta.helm.valueFiles) | default (list) }}
            - {{ $valueFile | toJson }}
          {{- end }}
          {{- if and (hasKey $meta "helm") $meta.helm.parameters }}
          parameters: {{ $meta.helm.parameters | toJson }}
          {{- end }}
      syncPolicy: {{ default $defVal.syncPolicy (and (hasKey $meta "syncPolicy") $meta.syncPolicy) | toJson }}
      ignoreDifferences: {{ default $defVal.ignoreDifferences (and (hasKey $meta "ignoreDifferences") $meta.ignoreDifferences) | toJson }}
