apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stg-backend-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "All applications related to backend team for stg environment"
  sourceRepos:
    - "https://github.com/ardikabs/demo-argocd-applicationset.git"
  destinations:
    - namespace: "*"
      name: in-cluster
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
  orphanedResources:
    warn: true
