namespace: bar

deployments:
  backend:
    devel:
      enabled: true
      helm:
        valueFiles:
          - .values.devel.yaml
          - values.devel.yaml


    stg:
      enabled: true

      helm:
        valueFiles:
          - .values.stg.yaml
          - values.stg.yaml

    prd:
      enabled: false
