namespace: bar

clusters:
  backend:
    dev:
      enabled: true

    stg:
      enabled: true

      helm:
        valueFiles:
          - .values.stg.yaml
          - values.stg.yaml

        parameters:
          - name: disableCronJob
            value: "true"

    prd:
      enabled: false
