namespace: foobar

deployments:
  backend:
    devel:
      enabled: true

    stg:
      enabled: true

      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    prd:
      enabled: false

clusterExclusions:
  stg-backend-eks-cluster-2: true
