namespace: foobar

clusters:
  backend:
    dev:
      enabled: true

    stg:
      enabled: true

      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    prd:
      enabled: false
