apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stg-backend-apps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: git@github.com:ardikabs/argocd-applicationset-patterns.git
                    revision: HEAD
                    files:
                      - path: kustomize/*/*/stg/.argocd.yaml
                - list:
                    elements:
                      - cluster:
                          id: backend-1
                          name: stg-backend-eks-cluster-1
                          prefix: "stg-backend"
                          suffix: "1"
                          disabled: false
                      - cluster:
                          id: backend-2
                          name: stg-backend-eks-cluster-2
                          prefix: "stg-backend"
                          suffix: "2"
                          disabled: false
          - list:
              elements:
                - values:
                    skip: '{{ ne (dig "cluster" "id" "N/A" .) (index .path.segments 1) }}'
      selector:
        matchExpressions:
          - key: cluster.disabled
            operator: NotIn
            values:
              - "true"

          - key: values.skip
            operator: NotIn
            values:
              - "true"

          - key: metadata.enabled
            operator: In
            values:
              - "true"
  template:
    metadata:
      name: "{{ .cluster.prefix }}-{{ index .path.segments 2 }}-{{ .cluster.suffix }}"
      annotations:
        applicationset/params: "{{ . | toJson }}"
      labels:
        platform.ardikabs.com/env: "staging"
        platform.ardikabs.com/envAlias: "stg"
        platform.ardikabs.com/cluster: "{{ .cluster.name }}"
        platform.ardikabs.com/service: "{{ index .path.segments 2 }}"
    spec:
      project: stg-backend-apps
      source:
        repoURL: git@github.com:ardikabs/argocd-applicationset-patterns.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        name: "{{ .cluster.name }}"
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |-
    {{- $argocd := .argocd }}

    metadata:
    {{- if hasKey $argocd "annotations" }}
      annotations: {{ $argocd.annotations | toJson }}
    {{- else }}
      annotations: {}
    {{- end }}

    {{- if and (hasKey $argocd "cleanupOnDeletion") ($argocd.cleanupOnDeletion) }}
      finalizers: ["resources-finalizer.argocd.argoproj.io"]
    {{- else }}
      finalizers: []
    {{- end}}

    {{- if hasKey $argocd "labels" }}
      labels: {{ $argocd.labels | toJson }}
    {{- else }}
      labels: {}
    {{- end }}

    spec:
      destination:
        {{- if hasKey $argocd "namespace" }}
        namespace: {{ $argocd.namespace }}
        {{- else }}
        namespace: "default"
        {{- end }}

      {{- if hasKey $argocd "syncPolicy" }}
      syncPolicy: {{ $argocd.syncPolicy | toJson }}
      {{- end }}

      {{- if hasKey $argocd "ignoreDifferences" }}
      ignoreDifferences: {{ $argocd.ignoreDifferences | toJson }}
      {{- end }}
