apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stg-backend-apps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: git@github.com:ardikabs/argocd-applicationset-patterns.git
                    revision: HEAD
                    files:
                      - path: helm/*/.argocd.yaml
                    values:
                      environment: "stg"
                      domain: "backend"
                - clusters:
                    selector:
                      matchLabels:
                        env: "{{ .values.environment }}"
                        domain: "{{ .values.domain }}"
          - git:
              repoURL: git@github.com:ardikabs/argocd-applicationset-patterns.git
              revision: HEAD
              files:
                - path: helm/runtimes.yaml
              values:
                clusterName: "{{ .name }}"
                clusterSuffix: '{{ index .metadata.labels "cluster/suffix" }}'
                enabled: '{{ dig .values.domain .values.environment "enabled" false .deployments | default false }}'
      selector:
        matchExpressions:
          - key: deployments.backend.stg.enabled
            operator: In
            values:
              - "true"
  template:
    metadata:
      name: "{{ .values.environment }}-{{ .values.domain }}-{{ index .path.segments 1 }}-{{ .values.clusterSuffix }}"
      annotations:
        applicationset/params: "{{ . | toJson }}"
      labels:
        systems.ardikabs.com/service: "{{ index .path.segments 1 }}"
        systems.ardikabs.com/cluster: "{{ .values.clusterName }}"
        systems.ardikabs.com/env: "{{ .values.environment }}"
        systems.ardikabs.com/domain: "{{ .values.domain }}"
      namespace: argocd
    spec:
      project: stg-backend-apps
      source:
        repoURL: git@github.com:ardikabs/argocd-applicationset-patterns.git
        targetRevision: HEAD
        path: "helm/{{ index .path.segments 1 }}"
        helm:
          releaseName: "{{ index .path.segments 1 }}"
      destination:
        name: "{{ .values.clusterName }}"
        namespace: "{{ .namespace }}"
  templatePatch: |-
    {{- $globals := .globals }}
    {{- $defVal := dig .values.environment dict .defaults.environments }}
    {{- $runtime := dig .values.clusterName dict .clusters }}
    {{- $svc := dig .values.domain .values.environment dict .deployments }}

    spec:
      source:
        helm:
          valueFiles: {{ default $defVal.helm.valueFiles (dig "helm" "valueFiles" list $svc) | toJson }}

          {{- $runtimeHelmParameters := dig "helm" "parameters" list $runtime }}
          {{- $svcHelmParameters := dig "helm" "parameters" list $svc }}
          parameters: {{ concat $runtimeHelmParameters $svcHelmParameters | toJson }}

      syncPolicy: {{ default $defVal.syncPolicy (dig "syncPolicy" dict $svc) | toJson }}

      {{- $svcIgnoreDifferences := dig "ignoreDifferences" list $svc }}
      {{- $ignoreDifferences := concat $globals.ignoreDifferences $svcIgnoreDifferences }}
      ignoreDifferences: {{ $ignoreDifferences | toJson }}
