apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stg-backend-app-dynamic-multicluster
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: git@github.com:ardikabs/demo-argocd-applicationset.git
                    revision: HEAD
                    directories:
                      - path: helm/*
                      - path: helm/*/templates
                        exclude: true
                      - path: helm/base
                        exclude: true
                - list:
                    elements:
                      - cluster:
                          name: stg-backend-eks-cluster-1
                          prefix: "stg-backend"
                          suffix: "1"
                          disabled: false
                        values:
                          # exclude - defines a blocklist mechanism; items listed here will be skipped.
                          # this is mutually exclusive with `include`. If both are defined, `include` takes precedence.
                          exclude: {}

                          # include - defines an allowlist mechanism; only explicitly listed items will be included.
                          # this is mutually exclusive with 'exclude'
                          # Ideally used in a bootstrapping phase
                          include: {}

                      - cluster:
                          name: stg-backend-eks-cluster-2
                          prefix: "stg-backend"
                          suffix: "2"
                          disabled: false
                        values:
                          # exclude - defines a blocklist mechanism; items listed here will be skipped.
                          # this is mutually exclusive with `include`. If both are defined, `include` takes precedence.
                          exclude: {}
                          #   foo: true
                          #   barfoo: true
                          #   bar: true

                          # include - defines an allowlist mechanism; only explicitly listed items will be included.
                          # this is mutually exclusive with 'exclude'
                          # Ideally used in a bootstrapping phase
                          include: {}
                          #   foo: true
                          #   barfoo: true
                          #   bar: true
          - list:
              elements:
                - values:
                    skip: '{{ dig "values" "exclude" (index .path.segments 1) false . }}'
                    keep: '{{ dig "values" "include" (index .path.segments 1) (empty .values.include) . }}'
      selector:
        # For an Application to be generated, the following conditions must be met:
        # - `values.skip` is not set to `true`: If true, the application creation is intentionally skipped.
        # - `values.keep` is set to `true`: Explicitly marks the application for creation, regardless of other conditions.
        # - `cluster.disabled` is not set to `true`: Ensures the target cluster is active and eligible for deployment.
        matchExpressions:
          - key: values.skip
            operator: NotIn
            values:
              - "true"

          - key: values.keep
            operator: In
            values:
              - "true"

          - key: cluster.disabled
            operator: NotIn
            values:
              - "true"
  template:
    metadata:
      name: "{{ .cluster.prefix }}-{{ index .path.segments 1 }}-{{ .cluster.suffix }}"
      annotations:
        applicationset/params: "{{ . | toJson }}"
    spec:
      project: stg-backend-apps
      source:
        repoURL: git@github.com:ardikabs/demo-argocd-applicationset.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
        helm:
          releaseName: "{{ index .path.segments 1 }}"
          valueFiles:
            - ../base/values.yaml
            - values.stg.yaml
            - .values.stg.yaml
          parameters:
            - name: eksCluster
              value: "1"
            - name: disableCronJob
              value: "false"
      destination:
        name: "{{ .cluster.name }}"
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
